### ISSUE TITLE
Summary page > pale yellow annotations box > can't click 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#419]
![2019 09 30_olc_summary page_annotations box](https://cloud.githubusercontent.com/assets/14910764/10203066/00ee6df0-6782-11e5-9224-7207e84a43f4.png)

When I click on any of the annotation fields listed in the pale yellow box on the top right hand corner of the summary page, nothing happens. I have tried this using Chrome, Safari and Internet Explorer. 

@KaitlinCCSI @SamCCSI @anderspeders

**Comment by anjesh** [comment]
Fixed.

**Comment by JesseCCSI** [comment]
Hi @anjesh for some reason I still can't click on anything in the pale yellow box? 

cc @KaitlinCCSI @SamCCSI
