### ISSUE TITLE
Why do the following unused properties exist?

### ISSUE THREAD

**Issue by jpmckinney** [NRGI/resourcecontracts.org#732]
Some properties are never set in any API records, so I don’t know why they exist. Please justify the following properties:

- deal_no
- deal_number
- matrix_page
- translation_parent
- company_identifier (seems to duplicate company_number)

**Comment by sadhakbj** [comment]
Fixed.

Please check the latest API here: 
http://rc-api-stage.elasticbeanstalk.com/api/contract/1152/metadata

**Comment by jpmckinney** [comment]
I still see `deal_number` and `matrix_page` - and no one has explained what those are for.

**Comment by KaitlinCCSI** [comment]
Perhaps one/both related to "Land Matrix ID", which we haven't yet begun
filling out but will do this month for OLC?

On Thu, Jan 7, 2016 at 7:23 AM, James McKinney <notifications@github.com>
wrote:

> I still see deal_number and matrix_page - and no one has explained what
> those are for.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/732#issuecomment-169661943>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01Q31njcD&m=14e8813c247b&t=20160107&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01Q31njcD&m=14e8813c247b&t=20160107&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01Q31njcD&m=14e8813c247b&t=20160107&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by anjesh** [comment]
Yes both are related to "Land Matrix" here https://github.com/NRGI/resourcecontracts.org/issues/606 and it's for OLC only and is displayed in the OLC site.
