### ISSUE TITLE
Annotations download csv

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#785]
The "annotations download" CSV files should be re-thought. Having all info (category, topic, annotation text, PDF page number) in the same column makes it very difficult to read, particularly given that the categories are all in English and French. Is there a reason why we couldn't make it like the other CSV files, with different types of info provided in separate columns?
![screen shot 2016-02-25 at 3 34 38 pm](https://cloud.githubusercontent.com/assets/14825437/13335233/9c337b1c-dbd5-11e5-8516-e3fce40827e8.png)

**Comment by anjesh** [comment]
Will be fixed after this issue https://github.com/NRGI/resourcecontracts.org/issues/764

**Comment by upasna01** [comment]
This issue have been fixed. Please review changes.

**Comment by KaitlinCCSI** [comment]
Looks much better; thanks. I don't know if you can control this, but if you can make Column A more narrow and Column C more wide, it would be even easier to read, as currently there is a lot of blank space in Column A and then the annotations are scrunched together in Column B.

![screen shot 2016-03-01 at 7 08 18 am](https://cloud.githubusercontent.com/assets/14825437/13427899/8853d128-df7c-11e5-8768-09a0d6477a54.png)

**Comment by jedm** [comment]
Regarding Annotations download available from Search results page, some elements spec-ed with Anders still not available:

- need unique URL of contract
- need boilerplate text noting original of this information (1-line explanation of RC/OLC and repeat of Contract unique URL)

Also, regarding the Download menu, recommend changing to:

PDF
MS WORD
MS EXCEL (Annotations Only)  

@anderspeders @charlesyoung please suggest any alternative wording you prefer

![screen shot 2016-04-10 at 6 29 03 pm](https://cloud.githubusercontent.com/assets/2153664/14414590/29415366-ff4a-11e5-8b2f-933ec757fe14.png)

**Comment by charlesyoung** [comment]
@jedm I agree with your download menu suggestions.

**Comment by jedm** [comment]
Cool, thanks Charles. 

@anjesh, if others agree with the Download menu adjustment, is it possible to put a line-break before "(Annotations only)"? Possible to make italic? (Will look better than with parentheses.)

**Comment by upasna01** [comment]
The text for download is changed, please verify.

http://www.resourcecontracts.org/search?q=

![785](https://cloud.githubusercontent.com/assets/11477899/16575197/fc3a274a-42a5-11e6-98d0-d7825ca972fc.png)

**Comment by SamCCSI** [comment]
I just performed this search: http://www.openlandcontracts.org/search?q=&document_type%5B0%5D=Contract&annotation_category%5B0%5D=Signatories%2C+State&order=asc&sortby=country

I then tried to download a csv file with all of these results by clicking the download button, but the CSV was blank.

![image](https://cloud.githubusercontent.com/assets/12913915/23084320/b90f2f64-f52f-11e6-893a-ae34733ce46c.png)

**Comment by manishgs** [comment]
This issue was on category names which consist of comma (,). Now it is fixed.

**Comment by SamCCSI** [comment]
Thanks @manishgs -- now working for me too.
