### ISSUE TITLE
MT did not auto reset

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#795]
For some reason this contract has been sitting untranscribed, but did not auto-reset. Can you fix this for this contract and every other idle contract?

http://resourcecontracts.elasticbeanstalk.com/mturk/681

Also, I checked a box in the warning pop-up when manually resetting page 1 and now I can't reset any other buttons (no warning pop up appears). Is there an easy way to get these pop ups back?

**Comment by SamCCSI** [comment]
Another example of the exact same problem: http://resourcecontracts.elasticbeanstalk.com/mturk/682

Do you know why these aren't auto-resetting?

**Comment by manishgs** [comment]
We had auto reset HIT feature (cron) for expired HIT but we disabled it because we got lots of error messages from mturk due to not enough balance in mturk account. Now we are thinking manual reset HITs of a contract instead of auto-reset. We'll have a button to reset all expired HIT and the tasks which haven't HIT yet.

![screenshot from 2016-03-03 17 08 21](https://cloud.githubusercontent.com/assets/3942999/13492865/9c8c09c0-e162-11e5-9682-996ac6b8653b.png)


![screenshot from 2016-03-03 17 13 50](https://cloud.githubusercontent.com/assets/3942999/13492990/59a0e148-e163-11e5-82bc-84d7a64a3a7e.png)


Let me know what do you think? @SamCCSI @anderspeders

**Comment by SamCCSI** [comment]
@anderspeders I liked the auto-reset idea -- Much less manual review needed. Is it not an option to always have a larger buffer of MT credit?

**Comment by SamCCSI** [comment]
@manishgs any suggestions for the second part of my query? _ I checked a box in the warning pop-up when manually resetting page 1 and now I can't reset any other buttons (no warning pop up appears). Is there an easy way to get these pop ups back?_

**Comment by manishgs** [comment]
I did reset for couple of HIT. I can see warning alert box and HIT reset successfully. 

![screenshot-resourcecontracts elasticbeanstalk com 2016-03-04 09-46-16](https://cloud.githubusercontent.com/assets/3942999/13517692/20fc73da-e1ee-11e5-8836-85d0d3647502.png)

Can you please try again? It should work.

**Comment by SamCCSI** [comment]
@manishgs working now, many thanks.

@anderspeders your thoughts on auto-reset?

**Comment by anderspeders** [comment]
This sounds good to me.

**Comment by SamCCSI** [comment]
@anderspeders are you saying auto-reset sounds good? If so, can we put this into action again and top up the amount of credits sitting in MT so that we don't exhaust funds?

**Comment by anderspeders** [comment]
@SamCCSI: As I understand we currently have enough funds on the account. 

@manishgs: Can we set up a notification when the cash available is getting low?

**Comment by manishgs** [comment]
@anderspeders  We already had that feature. If balance is less than 50 then system will send email to  resourcecontracts@yipl.com.np.

**Comment by SamCCSI** [comment]
Thanks @manishgs. In line with @anderspeders' instructions can you please confirm when you have re-enabled the auto-reset feature?

**Comment by manishgs** [comment]
We are going to incorporate following changes on existing auto-reset command.
1. reset task which has not HIT ID yet.
2. reset HIT on 31st days from created date 
3. If HIT is already approved by Mturk due to no action taken for submitted assignment for 30 days then task will set to approved.
4. Check for sufficient balance before resetting HIT.

**Comment by anderspeders** [comment]
Thanks @manishgs, 

@SamCCSI: this process should now be confirmed. I have just reconfirmed available funds. 

Closing this ticket.

**Comment by SamCCSI** [comment]
This doesn't appear to be functioning yet -- still finding contracts with many pages as not being reset. Also the 'reset all' button isn't present for some of these?

Eg: http://resourcecontracts.elasticbeanstalk.com/mturk/683

**Comment by KaitlinCCSI** [comment]
Re-opening to address Sam's comment

**Comment by manishgs** [comment]
done.

**Comment by SamCCSI** [comment]
@manishgs this contract still does not have a 'reset all' button: http://resourcecontracts.elasticbeanstalk.com/mturk/683

(or does the button only appear when hits 'expire'?)

**Comment by KaitlinCCSI** [comment]
re-opening for Sam's comment above

**Comment by manishgs** [comment]
> @anderspeders are you saying auto-reset sounds good? If so, can we put this into action again and top up the amount of credits sitting in MT so that we don't exhaust funds?

As you requested we have implemented auto-reset featured. The Mturk reset command is running everyday and priority set to less number of contract to be reset first.

**Comment by anderspeders** [comment]
@manishgs Can you clarify what this means?

As I see it we still have overdue hits - which have *not* reset after ten days?
![image](https://cloud.githubusercontent.com/assets/1101585/14740115/84e0e524-085a-11e6-8846-5467abb74fe5.png)

**Comment by charlesyoung** [comment]
I had the same issue yesterday with the Sierra Leone contracts. @anjesh was looking at the issue.

**Comment by manishgs** [comment]
@anderspeders 
> As I see it we still have overdue hits - which have not reset after ten days?

 HIT auto reset after 31 days from created date not the ten days.

**Comment by charlesyoung** [comment]
@manishgs I thought it was 10 days. My feeling is that 31 days is too long. 

cc @anderspeders

**Comment by charlesyoung** [comment]
@anderspeders can we agree to set the HIT auto reset after 10 days and not 31 days?

**Comment by charlesyoung** [comment]
The MTurk available balance is only $0.28 which means no HIT resets (auto or manual) are allowed. How can this problem be sorted out because it seems to be a monthly occurrence?

cc @anderspeders @anjesh

**Comment by manishgs** [comment]
Further discussion on #930
