### ISSUE TITLE
Changes to annotation module: hovering annotation window

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#852]
1. Delete "Related Annotations" from the hovering annotation window.
2. Delete the art. ref directly following the text in the hovering annotation window.
3. Delete the "Page x >>" hyperlink from the the hovering annotation window.
4. ALL article and page references to be included in the bottom line of both the annotation window.
5. Each page hyperlink should only contain the articles that are contained on that page — articles appearing on other pages should not be included in the brackets of that page.

Result: the hovering window should look like this:

![image](https://cloud.githubusercontent.com/assets/12913915/14540981/b0f76652-0255-11e6-95a7-657a20c97172.png)

**Comment by manishgs** [comment]
fixed.

**Comment by SamCCSI** [comment]
@manishgs this is not fixed. See screenshot: 
![image](https://cloud.githubusercontent.com/assets/12913915/14966593/47f787ba-1081-11e6-8a63-eab213fb8ce7.png)

Things in red ovals need to be removed, and all article and page references should be listed once in the bottom row as per this example (mentioned above)
![image](https://cloud.githubusercontent.com/assets/12913915/14966598/4f9d7a38-1081-11e6-8f93-185f1151ea47.png)
