### ISSUE TITLE
View all annotations error

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#915]
From a civil society user:

I was going through your very helpful database and spotted a potential technical glitch concerning the “view all annotation” link.

For instance, if I go on that link http://www.openlandcontracts.org/countries/sl and try to click on  the “view all annotations” link I get an error message (namely: "404! The page you’re looking for doesn't exist  If you’re looking for contract documents, use the search box above”). No doubt this is not serious but I thought that you might wish to know about it.

![image](https://cloud.githubusercontent.com/assets/12913915/16149887/afe686e2-3461-11e6-89fd-700980163dc4.png)

**Comment by hello-deepak** [comment]
Fixed.
http://www.resourcecontracts.org/countries/ao

![annotation](https://cloud.githubusercontent.com/assets/7577697/16193123/055ae50c-370d-11e6-8b71-da0d6c1b01e1.png)

**Comment by jedm** [comment]
Deepak and Sam,

The functionality here is inconsistent with the site in several ways (title is not bold, icon is a link here even though it is not in main search tool, link included in hover - which we decided against as a policy). 

Easiest fix is to:
- make doc name bold as in main search pages
- remove second sentence and link from hover on annotation icon

Thanks. 

Jed

**Comment by jedm** [comment]
Please also correct your English in the hover. The word "an" is missing.

**Comment by SamCCSI** [comment]
CCSI is happy with @jedm 's proposed changes.

**Comment by hello-deepak** [comment]
Please review this feature [here](http://www.resourcecontracts.org/countries/al)

**Comment by SamCCSI** [comment]
Thanks. Can you please change the hover to "This contract has annotations."

**Comment by hello-deepak** [comment]
Fixed.

**Comment by SamCCSI** [comment]
@hello-deepak not fixed. Hover should say "This contract has annotations." and not have any hyperlinks. On OLC it still has the hyperlink. This needs to be removed.

![image](https://cloud.githubusercontent.com/assets/12913915/16698888/b5eeb21c-451e-11e6-95e6-2a42fa6f25ed.png)

**Comment by hello-deepak** [comment]
Hyperlinks from OLC has removed.

**Comment by SamCCSI** [comment]
Thanks @hello-deepak
